---
title: "Tarea 01"
author: "Ximena Alvarado - 130849"
date: "January 15, 2015"
output: html_document
---

### Introducción al formato R Markdown

Ejemplo elaborado en `r date()`

```{r Paquetes}
library(ggmap)
```
```{r GenerarDatos, message=FALSE}
# Llenar información (sólo lo que está entre "").
clave.unica <- rep("130849",3)
# 1: Si es mixto, 0: no lo es. 
es.mixto <- c(universidad = 1, preparatoria = 1, secundaria = 1)
#Llenar con la dirección.
universidad <- geocode("ITAM")
preparatoria <- geocode("San Juan de Dios 6, Tlalpan, Ex - Hacienda de San Juan 14370 ")
secundaria <- geocode ("Algodonales 56, Riconada Coapa, 14330 Tlalpan, D.F.")
#Generamos la información
educacion <- rbind(universidad, preparatoria, secundaria)
educacion <- cbind(clave.unica, es.mixto, educacion)
```

```{r ObtenciónCoordenadasYMapas, warning=FALSE, message=FALSE}
limites <- make_bbox(lon, lat, educacion, f = 0.7)
mapa <- get_map(location = limites,
                maptype = "roadmap", 
                source = "google")
```

```{r GraficarLocalizaciones, echo=FALSE}
ggmap(mapa) +
  geom_point(data = educacion, 
             aes(x = lon, y= lat), 
             size = 4, alpha = 0.6, colour = "red")
```